server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        #配置存储配置信息的Git仓库
        git:
          uri: https://gitee.com/alexhuang/springcloud-config.git
          username: alex
          password: 123456
          #开启启动时直接从git获取配置
          clone-on-start: true
          #config子目录中的配置对应config应用
          #search-paths: '{application}'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/